// <auto-generated />
using Api_Angular;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api_Angular.Migrations
{
    [DbContext(typeof(AngularDbContext))]
    [Migration("20251206165610_inicial")]
    partial class inicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Api_Angular.Models.cantonModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("provinciaId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("provinciaId");

                    b.ToTable("Cantones");
                });

            modelBuilder.Entity("Api_Angular.Models.direccionModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("callePrincipal")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("calleSecundaria")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("cantonId")
                        .HasColumnType("int");

                    b.Property<string>("numero")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.HasIndex("cantonId");

                    b.ToTable("Direcciones");
                });

            modelBuilder.Entity("Api_Angular.Models.paisModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("id");

                    b.ToTable("Paises");
                });

            modelBuilder.Entity("Api_Angular.Models.provinciaModel", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("paisId")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("paisId");

                    b.ToTable("Provincias");
                });

            modelBuilder.Entity("Api_Angular.Models.cantonModel", b =>
                {
                    b.HasOne("Api_Angular.Models.provinciaModel", "Provincia")
                        .WithMany()
                        .HasForeignKey("provinciaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("Api_Angular.Models.direccionModel", b =>
                {
                    b.HasOne("Api_Angular.Models.cantonModel", "Canton")
                        .WithMany()
                        .HasForeignKey("cantonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Canton");
                });

            modelBuilder.Entity("Api_Angular.Models.provinciaModel", b =>
                {
                    b.HasOne("Api_Angular.Models.paisModel", "Pais")
                        .WithMany()
                        .HasForeignKey("paisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pais");
                });
#pragma warning restore 612, 618
        }
    }
}
